#!/usr/bin/env sh

alias g='git'

alias ls='eza --color=auto'
alias la='ls -la'
alias lah='ls -lah'
alias tree='ls -T --git-ignore'

alias rm='rm -i'

alias vim='nvim'

# ghq-tmux-session: pick an ghq repo/worktree and create/switch a tmux session
alias gts='ghq-tmux-session'

alias pacman='sudo pacman'
