#!/usr/bin/env sh

alias ls='exa --color=auto'
alias la='ls -la'
alias lah='ls -lah'
alias tree='ls -T --git-ignore'

alias rm='rm -i'

alias vim='nvim'

alias docker='sudo docker'
alias pacman='sudo pacman'
