# bash-completion
if [ ! -v BASH_COMPLETION_VERSINFO ]; then
    echo '$BASH_COMPLETION_VERSINFO is not set.' 1>&2
fi

# set keybind as 'vi'
set -o vi
# set vim as default editor
export EDITOR=/usr/bin/vim

# cargo env
. "$HOME/.cargo/env"

# fnm(Fast Node Maneger)
eval "$(fnm env)"

# Use eog with SSH-X11Forwarding
[ "$DISPLAY" ] && \
	alias eog='eog --display=$DISPLAY'

# GnuPG (with Agent) setup
export GPG_TTY=$(tty)
