#!/usr/bin/env bash
# custom rcfiles dir
__cwd=$(realpath $(dirname "${BASH_SOURCE}"))
# set alias from './aliases'
source "${__cwd}/aliases"
source "${__cwd}/fzfrc"
source "${__cwd}/batrc"

# bash-completion
if [ ! -v BASH_COMPLETION_VERSINFO ]; then
    echo '$BASH_COMPLETION_VERSINFO is not set.' 1>&2
fi

# Add PATH '~/.local/bin'
case ":${PATH}:" in
    *:"${HOME}/.local/bin":*)
        ;;
    *)
        export PATH="${HOME}/.local/bin:${PATH}"
        ;;
esac

# set keybind as 'vi'
set -o vi
# set vim as default editor
export EDITOR=/usr/bin/vim

# cargo env
. "$HOME/.cargo/env"

# fnm(Fast Node Maneger)
eval "$(fnm env)"

# Use eog with SSH-X11Forwarding
[ "$DISPLAY" ] && \
	alias eog='eog --display=$DISPLAY'

# GnuPG (with Agent) setup
export GPG_TTY=$(tty)

# aws profile aliases
function __set_profile_aws_clis () {
    if [[ ":$(aws configure list-profiles | paste -s -d: -):" =~ ":$1:" ]] ; then
        alias aws="aws --profile $1"
        alias cdk="cdk --profile $1"
        echo -e "Make Aliases:\n- \`aws = aws --profile $1\`\n- \`cdk = cdk --profile $1\`"
    else
        echo "Error \"$1\" was not found in \`aws configure --list-profiles\`" 1>&2
        return 1
    fi
}
alias aws-profiler='__set_profile_aws_clis'
