#!/usr/bin/env bash
# source completion and key-bindings
confdir='/usr/share/fzf'
if [ -d "${confdir}" ] ; then
    source "${confdir}/completion.bash"
    source "${confdir}/key-bindings.bash"
else
    echo "fzf completion and key-bindings files are not found [search for ${confdir}]." 1>&2
fi
unset confdir

# fzf-defult and key-bindings command
# fzf use fd as default
export FZF_DEFAULT_COMMAND='fd --type f --follow --hidden --exclude .git'
# Ctrl-T is used to shorten the imput of '$(fzf)'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_ALT_C_COMMAND="fd --type d --follow --max-depth=4"

# fzf command options
__auto="--select-1 --exit-0" # auto select or auto exit
# file preview using bat, see https://github.com/sharkdp/bat/blob/master/doc/README-ja.md#fzf
__file_preview="--preview 'bat --color=always --style=numbers --line-range=:500 {}'"
__dir_preview="--preview 'exa --tree --level 3 --color=always {} | head -100'"

export FZF_DEFAULT_OPTS="${__auto} --height 40% --reverse --border=rounded"
# these opts `inherit` FZF_DEFAULT_OPTS
export FZF_CTRL_T_OPTS="${__file_preview}"
export FZF_ALT_C_OPTS="${__dir_preview}"

unset __auto __file_preview __dir_preview

# fzf-completions
# Policy: NOT to target hidden files

# WARN: default '**' is comflict with zprezto
export FZF_COMPLETION_TRIGGER='``'
# fzf-completion does not look for hidden files
_fzf_compgen_path() {
  fd --follow . "$1"
}
_fzf_compgen_dir() {
  fd --type d --follow . "$1"
}

_fzf_comprun() {
  local command=$1
  shift

  case "$command" in
    cd)     fzf "$@" --preview 'exa --tree --level 3 --color=always {} | head -100' ;;
    *)      fzf "$@" ;;
  esac
}
